alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
drop table if exists Stuff cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Class_Student drop constraint FKhcxqus7alhtujwkt9vrskl96u
alter table Class_Student drop constraint FKiyrdd7o3adlxvqvasphgo0jsh
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists Class_Student cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phoneNumber drop constraint FKgdfqpl2g31hcsqof0xv8piekb
alter table Student drop constraint FK9vd8xbfa7svgpshok5mmdep1x
drop table if exists Address cascade
drop table if exists Class cascade
drop table if exists phoneNumber cascade
drop table if exists Student cascade
